FROM elixir:1.14.1-slim AS build

ENV REFRESHED_AT 20220926T210646Z
RUN apt-get update
RUN apt-get install -y build-essential zstd git curl unzip

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

ENV LANG=C.UTF-8
ENV MIX_ENV=prod
