FROM elixir:1.14.3-slim AS build

ENV REFRESHED_AT 20230214T165737Z
RUN apt-get update
RUN apt-get install -y build-essential zstd git curl unzip

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

ENV LANG=C.UTF-8
ENV MIX_ENV=prod
