FROM elixir:1.11-slim AS build

ENV REFRESHED_AT 20210712T152504Z
RUN apt-get update
RUN apt-get install -y build-essential zstd git curl unzip procps

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

ENV LANG=C.UTF-8
ENV MIX_ENV=prod
