on:
  push:
    branches: [distribution-e2e-tests]

jobs:
  e2e:
    # We use this virtual environment because it supports nested virtualization.
    # See https://github.com/actions/virtual-environments/issues/433 for more
    # information
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('**/Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Vagrant base box update
        run: vagrant box update

      - name: Bring up the VM
        run: |
          cd ./dist/ubuntu/22.04
          vagrant up --provision

      - name: Run e2e
        run: vagrant ssh -c "echo 'hello world!'"

      - name: Destroy the VM
        run: vagrant destroy -f
