on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ['24.3.4.1']
        elixir: ['1.13.4']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
        version-type: strict

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: |
        epmd -daemon
        mix test

    # If the following is too slow, we can ditch it. Should only be slow once after an Erlang/Elixir version upgrade.
    - name: Retrieve Dialyzer PLT cache
      uses: actions/cache@v1
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles('**/mix.lock') }}-v2
    - name: Create Dialyzer PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt
    - name: Run Dialyzer
      run: MIX_ENV=test mix dialyzer --no-check

  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::147803588724:role/github-action
          aws-region: us-west-2
      - name: Fetch Secret into Env
        run: .github/secret-to-env.sh
      - name: Import signing key
        run: aws secretsmanager get-secret-value --secret-id /prod/gh-actions/signing-key --region us-west-2 | jq -r '.SecretString' | gpg --import
      - name: Build and Push Orchestrator container
        run: |
          dist/login.sh
          ./build-and-push.sh

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [test, build-push]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::147803588724:role/github-action
          aws-region: us-west-2
      - name: Fetch Secret into Env
        run: .github/secret-to-env.sh
      - name: Deploy Orchestrator container
        run: ./deploy.sh
