name: Develop nightly reset

on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop #checkout develop
          fetch-depth: 0
          token: ${{ secrets.RESET_PAT }} #PAT needed as per https://github.com/ad-m/github-push-action/issues/32 & https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
      - name: Reset develop to main nightly
        run: |
          git config --global user.email "nobodye@canarymonitor.com"
          git config --global user.name "Github Action Bot"
          git reset --hard origin/main && git commit --allow-empty -m "== Hard reset to main ==" && git push --force
