name: Develop nightly reset

on:
  schedule:
    - cron: '0 1 * * 1' # every Monday at 1am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop #checkout develop
          fetch-depth: 0
          token: ${{ secrets.RESET_PAT }} #PAT needed as per https://github.com/ad-m/github-push-action/issues/32 & https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
      - name: Create new base image
        run: |
          git config --global user.email "nobodye@canarymonitor.com"
          git config --global user.name "Github Action Bot"
          ./refresh-base.sh
